server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost/dr
    username: root
    password: "020313"
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 8
      max-active: 16
      min-idle: 1
      max-wait: 60000

mybatis:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: com.neu.pojo

logging:
  level:
    com.example: debug
